/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xuansu_com_appupdatedemo_Patch */

#ifndef _Included_xuansu_com_appupdatedemo_Patch
#define _Included_xuansu_com_appupdatedemo_Patch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xuansu_com_appupdatedemo_Patch
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xuansu_com_appupdatedemo_Patch_bsPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
